package elements

var AlienSpeciesDescriptorsTable = []string{
	"Advanced", // 1
	"Aggressive", // 2
	"Agile", // 3
	"Amphibious", // 4
	"Ancient", // 5
	"Anxious", // 6
	"Aquatic", // 7
	"Arrogant", // 8
	"Artistic", // 9
	"Avian", // 10
	"Beautiful", // 11
	"Bizarre", // 12
	"Carapace", // 13
	"Clawed", // 14
	"Colorful", // 15
	"Combative", // 16
	"Conquering", // 17
	"Dangerous", // 18
	"Declining", // 19
	"Defensive", // 20
	"Desperate", // 21
	"Destructive", // 22
	"Dominating", // 23
	"Emotionless", // 24
	"Enormous", // 25
	"Exploitive", // 26
	"Explorers", // 27
	"Familiar", // 28
	"Fast", // 29
	"Feeble", // 30
	"Feral", // 31
	"Ferocious", // 32
	"Friendly", // 33
	"Frightening", // 34
	"Fungal", // 35
	"Furry", // 36
	"Generous", // 37
	"Gentle", // 38
	"Glowing", // 39
	"Graceful", // 40
	"Harsh", // 41
	"Helpful", // 42
	"Humanoid", // 43
	"Hungry", // 44
	"Immortal", // 45
	"Insectlike", // 46
	"Insubstantial", // 47
	"Intelligent", // 48
	"Intimidating", // 49
	"Large", // 50
	"Lethal", // 51
	"Levitating", // 52
	"Liquid", // 53
	"Mammalian", // 54
	"Many-eyed", // 55
	"Militaristic", // 56
	"Mysterious", // 57
	"Nightmarish", // 58
	"Odd", // 59
	"Oppressive", // 60
	"Passive", // 61
	"Peaceful", // 62
	"Perfect", // 63
	"Plant", // 64
	"Powered", // 65
	"Powerful", // 66
	"Powers", // 67
	"Primitive", // 68
	"Prosperous", // 69
	"Psychic", // 70
	"Reptilian", // 71
	"Robotic", // 72
	"Scary", // 73
	"Scientific", // 74
	"Secretive", // 75
	"Servitor", // 76
	"Simple", // 77
	"Skilled", // 78
	"Slender", // 79
	"Slow", // 80
	"Small", // 81
	"Smelly", // 82
	"Strange", // 83
	"Strong", // 84
	"Suffering", // 85
	"Tail", // 86
	"Tall", // 87
	"Technological", // 88
	"Tentacled", // 89
	"Threatening", // 90
	"Toothy", // 91
	"Travelers", // 92
	"Treacherous", // 93
	"Violent", // 94
	"Warlike", // 95
	"Wary", // 96
	"Watery", // 97
	"Weak", // 98
	"Wings", // 99
	"Wormish", // 100
}
