package elements

var CivilizationDescriptorsTable = []string{
	"Active", // 1
	"Advanced", // 2
	"Adventurous", // 3
	"Aggressive", // 4
	"Agricultural", // 5
	"Ancient", // 6
	"Angry", // 7
	"Anxious", // 8
	"Artistic", // 9
	"Average", // 10
	"Beautiful", // 11
	"Bizarre", // 12
	"Bleak", // 13
	"Bold", // 14
	"Bureaucratic", // 15
	"Carefree", // 16
	"Careful", // 17
	"Careless", // 18
	"Cautious", // 19
	"Classy", // 20
	"Clean", // 21
	"Colorful", // 22
	"Combative", // 23
	"Commercial", // 24
	"Competitive", // 25
	"Constructive", // 26
	"Controlling", // 27
	"Crazy", // 28
	"Creative", // 29
	"Creepy", // 30
	"Cruel", // 31
	"Curious", // 32
	"Dangerous", // 33
	"Declining", // 34
	"Defiant", // 35
	"Delightful", // 36
	"Developed", // 37
	"Disagreeable", // 38
	"Distrustful", // 39
	"Dominant", // 40
	"Dull", // 41
	"Efficient", // 42
	"Expanding", // 43
	"Failed", // 44
	"Famous", // 45
	"Fearful", // 46
	"Festive", // 47
	"Free", // 48
	"Generous", // 49
	"Greedy", // 50
	"Happy", // 51
	"Healthy", // 52
	"Helpful", // 53
	"Helpless", // 54
	"Historical", // 55
	"Important", // 56
	"Industrial", // 57
	"Influential", // 58
	"Intolerant", // 59
	"Large", // 60
	"Lawful", // 61
	"Lawless", // 62
	"Magnificent", // 63
	"Mighty", // 64
	"Militaristic", // 65
	"Miserable", // 66
	"Modern", // 67
	"Mundane", // 68
	"Mysterious", // 69
	"Old", // 70
	"Open", // 71
	"Oppressive", // 72
	"Peaceful", // 73
	"Polite", // 74
	"Poor", // 75
	"Powerful", // 76
	"Primitive", // 77
	"Punitive", // 78
	"Quaint", // 79
	"Religious", // 80
	"Ruined", // 81
	"Rustic", // 82
	"Ruthless", // 83
	"Scary", // 84
	"Simple", // 85
	"Small", // 86
	"Strange", // 87
	"Strong", // 88
	"Struggling", // 89
	"Successful", // 90
	"Suffering", // 91
	"Suppressed", // 92
	"Suspicious", // 93
	"Treacherous", // 94
	"Warlike", // 95
	"Weak", // 96
	"Wealthy", // 97
	"Welcoming", // 98
	"Wild", // 99
	"Young", // 100
}
