package elements

var GodsTable = []string{
	"Active", // 1
	"Alien", // 2
	"Ancient", // 3
	"Angelic", // 4
	"Angry", // 5
	"Animal", // 6
	"Art", // 7
	"Assist", // 8
	"Attract", // 9
	"Beautiful", // 10
	"Bestow", // 11
	"Betray", // 12
	"Bizarre", // 13
	"Capricious", // 14
	"Colorful", // 15
	"Combat", // 16
	"Communicate", // 17
	"Conflict", // 18
	"Control", // 19
	"Corruption", // 20
	"Cosmic", // 21
	"Create", // 22
	"Creepy", // 23
	"Cruel", // 24
	"Cult", // 25
	"Dangerous", // 26
	"Dark", // 27
	"Death", // 28
	"Deceit", // 29
	"Destroyer", // 30
	"Disgusting", // 31
	"Dominate", // 32
	"Dreams", // 33
	"Elements", // 34
	"Emotions", // 35
	"Enemies", // 36
	"Energy", // 37
	"Enormous", // 38
	"Evil", // 39
	"Feminine", // 40
	"Fallen", // 41
	"Fear", // 42
	"Fertility", // 43
	"Festive", // 44
	"Fire", // 45
	"Frightening", // 46
	"Generous", // 47
	"Gentle", // 48
	"Gifts", // 49
	"Glorious", // 50
}
