package elements

var LocationTable = []string{
	"Abandoned",   // 1
	"Active",      // 2
	"Artistic",    // 3
	"Atmosphere",  // 4
	"Beautiful",   // 5
	"Bleak",       // 6
	"Bright",      // 7
	"Business",    // 8
	"Calm",        // 9
	"Charming",    // 10
	"Clean",       // 11
	"Cluttered",   // 12
	"Cold",        // 13
	"Colorful",    // 14
	"Colorless",   // 15
	"Confusing",   // 16
	"Cramped",     // 17
	"Creepy",      // 18
	"Crude",       // 19
	"Cute",        // 20
	"Damaged",     // 21
	"Dangerous",   // 22
	"Dark",        // 23
	"Delightful",  // 24
	"Dirty",       // 25
	"Domestic",    // 26
	"Empty",       // 27
	"Enclosed",    // 28
	"Enormous",    // 29
	"Entrance",    // 30
	"Exclusive",   // 31
	"Exposed",     // 32
	"Extravagant", // 33
	"Familiar",    // 34
	"Fancy",       // 35
	"Festive",     // 36
	"Foreboding",  // 37
	"Fortunate",   // 38
	"Fragrant",    // 39
	"Frantic",     // 40
	"Frightening", // 41
	"Full",        // 42
	"Harmful",     // 43
	"Helpful",     // 44
	"Horrible",    // 45
	"Important",   // 46
	"Impressive",  // 47
	"Inactive",    // 48
	"Intense",     // 49
	"Intriguing",  // 50
	"Lively",      // 51
	"Lonely",      // 52
	"Long",        // 53
	"Loud",        // 54
	"Meaningful",  // 55
	"Messy",       // 56
	"Mobile",      // 57
	"Modern",      // 58
	"Mundane",     // 59
	"Mysterious",  // 60
	"Natural",     // 61
	"New",         // 62
	"Occupied",    // 63
	"Odd",         // 64
	"Official",    // 65
	"Old",         // 66
	"Open",        // 67
	"Peaceful",    // 68
	"Personal",    // 69
	"Plain",       // 70
	"Portal",      // 71
	"Protected",   // 72
	"Protection",  // 73
	"Purposeful",  // 74
	"Quiet",       // 75
	"Reassuring",  // 76
	"Remote",      // 77
	"Resourceful", // 78
	"Ruined",      // 79
	"Rustic",      // 80
	"Safe",        // 81
	"Services",    // 82
	"Simple",      // 83
	"Small",       // 84
	"Spacious",    // 85
	"Storage",     // 86
	"Strange",     // 87
	"Stylish",     // 88
	"Suspicious",  // 89
	"Tall",        // 90
	"Threatening", // 91
	"Tranquil",    // 92
	"Unexpected",  // 93
	"Unpleasant",  // 94
	"Unusual",     // 95
	"Useful",      // 96
	"Warm",        // 97
	"Warning",     // 98
	"Watery",      // 99
	"Welcoming",   // 100
}
